# Generated by Django 2.0.13 on 2019-09-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fam_name', models.CharField(default='', max_length=100)),
                ('tarifa', models.TextField(choices=[('A', 'Adultos'), ('E', 'Estudiantes Ticos'), ('G', 'Grupos'), ('N', 'Ninos')], default='A')),
                ('res', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
