# Generated by Django 2.0.13 on 2019-09-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='client',
            field=models.TextField(choices=[('', '')], default=''),
        ),
    ]
