# Generated by Django 2.0.13 on 2019-09-18 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='lan',
            new_name='language',
        ),
    ]
