# Generated by Django 2.0.13 on 2019-09-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='client',
            field=models.IntegerField(blank=True, default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
