# Generated by Django 2.0.13 on 2019-09-25 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priceproduct',
            name='category',
        ),
    ]
