# Generated by Django 2.0.13 on 2019-09-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_reservation_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='res',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='name',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='client',
            field=models.TextField(choices=[('', ''), ('Justin', 'Justin')], default=''),
        ),
    ]
