# Generated by Django 2.0.13 on 2019-09-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190912_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='res',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
