# Generated by Django 2.0.13 on 2019-09-25 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_priceproduct_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Person'),
        ),
    ]
