# Generated by Django 2.0.13 on 2019-09-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190918_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='modified',
            field=models.TextField(default=''),
        ),
    ]
