# Generated by Django 2.0.13 on 2019-09-18 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_general_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('general_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.General')),
                ('act', models.TextField(default='')),
            ],
            bases=('app.general',),
        ),
        migrations.RemoveField(
            model_name='general',
            name='modified',
        ),
    ]
