# Generated by Django 2.0.13 on 2019-09-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_client_res'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='res',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='client',
        ),
        migrations.AddField(
            model_name='reservation',
            name='client',
            field=models.ManyToManyField(to='app.Client'),
        ),
    ]
