# Generated by Django 2.0.13 on 2019-09-25 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rate_agency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='priceproduct',
            old_name='net',
            new_name='net_ATEC',
        ),
        migrations.RemoveField(
            model_name='linereservation',
            name='cost_price',
        ),
        migrations.AddField(
            model_name='priceproduct',
            name='net_AGENCIA',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
