# Generated by Django 2.0.13 on 2019-09-19 16:44

import address.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190918_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languageperson',
            name='lang',
            field=models.CharField(default='ESPANOL', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.Address', unique=True),
        ),
        migrations.AlterField(
            model_name='typeperson',
            name='type',
            field=models.CharField(default='CLIENTE', max_length=100, unique=True),
        ),
    ]
