# Generated by Django 2.0.13 on 2019-09-26 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190925_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='agency',
        ),
        migrations.AddField(
            model_name='ratediscount',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Person'),
        ),
    ]
