# Generated by Django 2.0.13 on 2019-09-12 18:23

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190912_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
