# Generated by Django 2.0.13 on 2019-09-26 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190926_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priceproduct',
            name='tax_price',
        ),
        migrations.AddField(
            model_name='reservation',
            name='tax_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Tax'),
        ),
    ]
