# Generated by Django 2.0.13 on 2019-09-12 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_auto_20190912_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.TextField(choices=[('R', 'Realizada'), ('NR', 'No Realizada'), ('SB', 'Stand By'), ('A', 'Esperando el Administrador que debe hacerla'), ('G', 'Esperando la repuesta del guia')], default='NR')),
                ('guia', models.CharField(blank=True, max_length=100)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='categoria',
            field=models.TextField(choices=[('C', 'Clientos'), ('A', 'Agencia')], default='C'),
        ),
    ]
