# Generated by Django 2.0.13 on 2019-09-13 15:52

import address.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('address', '0002_auto_20160213_1726'),
        ('app', '0007_auto_20190912_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=1000)),
                ('Precio', models.PositiveIntegerField(default=0)),
                ('Duracion', models.TimeField(default=0)),
                ('Dificultad', models.TextField(choices=[('D', 'Dificil'), ('N', 'Normal'), ('F', 'Facil')], default='Normal')),
                ('Incluyo', models.TextField(default='')),
                ('Description', models.TextField(default='')),
                ('Localizacion', address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, to='address.Address')),
            ],
        ),
        migrations.RenameModel(
            old_name='Tareas',
            new_name='Tarea',
        ),
    ]
