# Generated by Django 2.0.13 on 2019-09-13 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20160213_1726'),
        ('app', '0008_auto_20190913_0952'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servicios',
            new_name='Servicio',
        ),
    ]
