# Generated by Django 2.0.13 on 2019-09-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190913_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='Duracion',
            field=models.DurationField(default=0),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='Localizacion',
            field=models.TextField(default=''),
        ),
    ]
