# Generated by Django 2.0.13 on 2019-09-26 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190926_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linereservation',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientXperson', to='app.Person'),
        ),
        migrations.AlterField(
            model_name='linereservation',
            name='guide',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineXguide', to='app.Person'),
        ),
        migrations.AlterField(
            model_name='linereservation',
            name='line_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineXproduct', to='app.Product'),
        ),
        migrations.AlterField(
            model_name='linereservation',
            name='line_reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineXreservation', to='app.Reservation'),
        ),
        migrations.AlterField(
            model_name='linereservation',
            name='sell_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineXprice', to='app.PriceProduct'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='per',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Person'),
        ),
        migrations.AlterField(
            model_name='paymentreservation',
            name='payment_reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paymentXreservation', to='app.Reservation'),
        ),
        migrations.AlterField(
            model_name='paymentreservation',
            name='type_payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.TypePayment'),
        ),
        migrations.AlterField(
            model_name='person',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.TypePerson'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='per',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Person'),
        ),
        migrations.AlterField(
            model_name='priceproduct',
            name='age_discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agediscount', to='app.AgeDiscount'),
        ),
        migrations.AlterField(
            model_name='priceproduct',
            name='price_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Product'),
        ),
        migrations.AlterField(
            model_name='priceproduct',
            name='rate_discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratediscount', to='app.RateDiscount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.StockProduct'),
        ),
        migrations.AlterField(
            model_name='ratediscount',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Person'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='tax_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservationXtax', to='app.Tax'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
