# Generated by Django 2.0.13 on 2019-09-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190913_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='image',
            field=models.ImageField(default='app/static/img/header-bg.jpg', upload_to='app/static/img'),
        ),
    ]
