# Generated by Django 2.0.13 on 2019-10-01 16:54

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190926_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linereservation',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='linereservation',
            name='date_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='priceproduct',
            name='rack',
            field=models.FloatField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
