# Generated by Django 2.0.13 on 2019-10-01 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20191001_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='linereservation',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='languageXline', to='app.LanguagePerson'),
        ),
    ]
