# Generated by Django 2.0.13 on 2019-09-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_servicio_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
