# Generated by Django 2.0.13 on 2019-10-01 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_linereservation_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linereservation',
            old_name='language',
            new_name='language_reservation',
        ),
    ]
