# Generated by Django 2.0.13 on 2019-10-02 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20191001_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATEC',
            fields=[
                ('general_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.General')),
                ('field_name', models.TextField(blank=True, default='Tours ONG ATEC', null=True)),
                ('field_cedjuri', models.TextField(blank=True, default='Céd.Juri: 3-002-118055', null=True)),
                ('field_tel_cellular', models.TextField(blank=True, default='+(506) 8706-4758.', null=True)),
                ('field_localisation', models.TextField(blank=True, default='Frente a Farmacia Caribe, bajo Mopri, Puerto Viejo Limon', null=True)),
                ('field_tel_officina', models.TextField(blank=True, default='Teléfono: +(506) 2750-0398', null=True)),
                ('field_mail', models.TextField(blank=True, default='Email: ongatec@gmail.com', null=True)),
                ('logo', models.ImageField(blank=True, default='img/ATEC_LOGO.png', null=True, upload_to='')),
                ('field_thanks', models.TextField(blank=True, default='Thank you for booking and supporting our NGO ATEC!', null=True)),
                ('field_recommandations', models.TextField(blank=True, default='Recommendations: apply repellent and sun block, closed shoes, bottle of water, camera, snacks, cash and in cases apply swimming suit, towel, jaket', null=True)),
                ('image_1', models.ImageField(blank=True, default='img/ict.jpeg', null=True, upload_to='')),
                ('image_2', models.ImageField(blank=True, default='img/codeofconduct.jpeg', null=True, upload_to='')),
                ('image_3', models.ImageField(blank=True, default='img/fb.jpeg', null=True, upload_to='')),
                ('image_4', models.ImageField(blank=True, default='img/tripadvisor.jpeg', null=True, upload_to='')),
                ('image_5', models.ImageField(blank=True, default='img/turismosostenible.jpeg', null=True, upload_to='')),
                ('link_1', models.TextField(blank=True, default='https://www.tripadvisor.com.mx/Attraction_Review-g309265-d2209012-Reviews-ATEC_Talamancan_Association_of_Ecotourism_and_Conservation_Day_Tours-Puerto_Viejo.html', null=True)),
                ('link_2', models.TextField(blank=True, default='https://www.facebook.com/atectalamanca/', null=True)),
                ('link_3', models.TextField(blank=True, default='', null=True)),
                ('link_4', models.TextField(blank=True, default='', null=True)),
                ('link_5', models.TextField(blank=True, default='', null=True)),
                ('size_1', models.TextField(blank=True, default='5%', null=True)),
                ('size_2', models.TextField(blank=True, default='5%', null=True)),
                ('size_3', models.TextField(blank=True, default='5%', null=True)),
                ('size_4', models.TextField(blank=True, default='5%', null=True)),
                ('size_5', models.TextField(blank=True, default='5%', null=True)),
            ],
            bases=('app.general',),
        ),
    ]
