# Generated by Django 2.0.13 on 2019-10-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20191002_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atec',
            name='logo',
            field=models.ImageField(blank=True, default='app/static/img/ATEC_LOGO.png', null=True, upload_to=''),
        ),
    ]
