# Generated by Django 2.0.13 on 2019-10-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20191002_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atec',
            name='logo',
            field=models.ImageField(blank=True, default='ATEC_LOGO.png', null=True, upload_to=''),
        ),
    ]
