# Generated by Django 2.0.13 on 2019-10-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20191002_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atec',
            name='image_1',
            field=models.ImageField(blank=True, default='img/ict.jpeg', null=True, upload_to='app/static/img'),
        ),
        migrations.AlterField(
            model_name='atec',
            name='image_2',
            field=models.ImageField(blank=True, default='img/codeofconduct.jpeg', null=True, upload_to='app/static/img'),
        ),
        migrations.AlterField(
            model_name='atec',
            name='image_3',
            field=models.ImageField(blank=True, default='img/fb.jpeg', null=True, upload_to='app/static/img'),
        ),
        migrations.AlterField(
            model_name='atec',
            name='image_4',
            field=models.ImageField(blank=True, default='img/tripadvisor.jpeg', null=True, upload_to='app/static/img'),
        ),
        migrations.AlterField(
            model_name='atec',
            name='image_5',
            field=models.ImageField(blank=True, default='img/turismosostenible.jpeg', null=True, upload_to='app/static/img'),
        ),
        migrations.AlterField(
            model_name='atec',
            name='logo',
            field=models.ImageField(blank=True, default='img/ATEC_LOGO.png', null=True, upload_to='app/static/img'),
        ),
    ]
