# Generated by Django 2.0.13 on 2019-10-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20191002_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='atec',
            name='size_logo',
            field=models.TextField(blank=True, default='120', null=True),
        ),
        migrations.AlterField(
            model_name='atec',
            name='image_1',
            field=models.ImageField(blank=True, default='tripadvisor.jpeg', null=True, upload_to='app/static/img'),
        ),
        migrations.AlterField(
            model_name='atec',
            name='image_2',
            field=models.ImageField(blank=True, default='fb.jpeg', null=True, upload_to='app/static/img'),
        ),
        migrations.AlterField(
            model_name='atec',
            name='image_3',
            field=models.ImageField(blank=True, default='codeofconduct.jpeg', null=True, upload_to='app/static/img'),
        ),
        migrations.AlterField(
            model_name='atec',
            name='image_4',
            field=models.ImageField(blank=True, default='ict.jpeg', null=True, upload_to='app/static/img'),
        ),
        migrations.AlterField(
            model_name='atec',
            name='link_2',
            field=models.TextField(blank=True, default='https://www.facebook.com/ongatec/', null=True),
        ),
        migrations.AlterField(
            model_name='atec',
            name='size_1',
            field=models.TextField(blank=True, default='90', null=True),
        ),
        migrations.AlterField(
            model_name='atec',
            name='size_2',
            field=models.TextField(blank=True, default='90', null=True),
        ),
        migrations.AlterField(
            model_name='atec',
            name='size_3',
            field=models.TextField(blank=True, default='60', null=True),
        ),
        migrations.AlterField(
            model_name='atec',
            name='size_4',
            field=models.TextField(blank=True, default='30', null=True),
        ),
        migrations.AlterField(
            model_name='atec',
            name='size_5',
            field=models.TextField(blank=True, default='44', null=True),
        ),
    ]
