# Generated by Django 2.0.13 on 2019-10-03 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_reservation_card_paypal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratediscount',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rateXagency', to='app.Person'),
        ),
    ]
