# Generated by Django 2.0.13 on 2019-10-03 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20191003_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='per',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailXper', to='app.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typeXper', to='app.TypePerson'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='per',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phoneXper', to='app.Person'),
        ),
    ]
