# Generated by Django 2.0.13 on 2019-10-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20191003_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='card_paypal',
        ),
        migrations.AddField(
            model_name='linereservation',
            name='card_paypal',
            field=models.BooleanField(default=False),
        ),
    ]
