# Generated by Django 2.0.13 on 2019-10-04 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20191004_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='COUPON',
            fields=[
                ('general_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.General')),
                ('numero', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='app/static/img')),
            ],
            bases=('app.general',),
        ),
    ]
